name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.7
      with:
        name: necgm/website
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
